# Site Settings
url: "teona-alex.wedding"
baseurl: ""
force-https: True
lang: "ro"
google-tracking-id: ""

# Build Settings
markdown: kramdown
exclude:
  - CONTRIBUTING
  - CONTRIBUTORS
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .gitignore
  - .travis.yml

theme: jekyll-theme-minimal