# Site Settings
url: "teona-alex.wedding"
baseurl: ""
paginate_path: blog/pagina-:num/
permalink: blog/:categories/:title/
force-https: True
lang: "ro"
paginate: 5
google-tracking-id: ""

# Build Settings
markdown: kramdown
highlighter: rouge
kramdown:
  input:            GFM
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  parse_block_html: true

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - CONTRIBUTING
  - CONTRIBUTORS
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .gitignore
  - .travis.yml
