# Site Settings
url: "teona-alex.wedding"
baseurl: ""
force-https: True
lang: "ro"
google-tracking-id: ""

# Build Settings
markdown: kramdown
highlighter: rouge
kramdown:
  input:            GFM
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  parse_block_html: true

exclude:
  - CONTRIBUTING
  - CONTRIBUTORS
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .gitignore
  - .travis.yml

theme: jekyll-theme-minimal